### PR TITLE
Nico

### PR DESCRIPTION
**Pull request by Oshi41**

### CODE REVIEW

**Comment by krwminer** [comment]
Are you changing the amount of OreGen by making it chance squared?
Also just a note, use "if (condition1) { } else if (condition2) {} else if (condition3) {} ..." when all of the conditions are mutually exclusive rather than just using ifs.

**Comment by NicosaurusRex99** [comment]
I think we should actually do this in the biome provider so we arent running multiple generators to do the same job

**Comment by Oshi41** [comment]
@krwminer 
Yes, I think we try to spawn ore much more
Config says how much ore tries to spawn
That what is happened on my algorythm (founded chunk with 6 ores)

As i understood Divine generated 2 veins per chunk with 2 ores
https://github.com/DivineRPG/DivineRPG/blob/master/java/net/divinerpg/dimensions/vanilla/DivineWorldgen.java
image

**Comment by Oshi41** [comment]
So i think we need to remove squared chance to ore spawn

**Comment by Oshi41** [comment]
@NicosaurusRex99 
We are injected WorldGenCustomOres as handler to spawn ore in vanilla worlds
We can't change already existing vanilla boime providers
And all logic with ore gen now is placing in one file, I can live with it

**Comment by NicosaurusRex99** [comment]
i was refering to our custom ones. vanilla we will have to inject

**Comment by Oshi41** [comment]
@NicosaurusRex99 
I meant this file is describes all ore spawn logic
Not only vanilla, yes
And all ore gen logic contains in one file not spread it to all code base

**Comment by Oshi41** [comment]
Mapped ids with ore spawning functions
Removed "if" tree

**Review by krwminer — APPROVED** [review]

**Review by NicosaurusRex99 — COMMENTED** [review]
We may remove the truffle idea as we totally forgot the point behind it. also we intend on redesigning the tree trunk

**Comment by Oshi41** [comment]
@NicosaurusRex99 
What do you mean tree gen in Skythern?

**Comment by NicosaurusRex99** [comment]
yeah, it was something krwminer and i had planned but we never really put alot of thought into it other than it would be used for crafting food

**Comment by Oshi41** [comment]
@NicosaurusRex99 
All right, I will remove it and push the request

**Pull request merged**
