### PR TITLE
Changed entity register to use registry event, add spawn egg color sy…

### PR DESCRIPTION
**Pull request by AstralScourge**
Added a color system for the spawn eggs, instead of being a gradually darker (lighter?) shade of blue they are colored by the dimension they are in.

Also used the registry event to register the mobs, as recommended here (currently it uses the older registry method it recommends against)
https://mcforge.readthedocs.io/en/latest/concepts/registries/
Didn't touch the registration for non-mob entities (projectiles) or anything else yet.

Also, before, the mob ids all took the format of "divinerpg:divinerpg.cyclops". The second divinerpg has no reason to be there so I removed it, and now the entity IDs are just "divinerpg:cyclops" for instance. This will cause older saves to complain that "divinerpg:divinerpg.cyclops" and every other mob is not present, but the mod isn't out yet, and better now than when it is.

Below video is proof that I didn't break anything. As seen in the video, though, the mob models, loot tables, stats, etc. are still intact.
https://youtu.be/o_fLsAIt5NM

### CODE REVIEW

**Review by NicosaurusRex99 — CHANGES_REQUESTED** [review]
We include the modid in entity names so we do not have mod incompatability issues.

**Comment by AstralScourge** [comment]
editing this comment rn

**Comment by AstralScourge** [comment]
The mod identifier is supposed to prevent the ID conflicts, and if mobs having the same id across different mods with different mod ids was a problem I'd expect it would have been noticed by now.

After consulting with some others though I'm pretty sure I have it figured out.

I assume that the issue you are talking about is the one found in these two issues:
https://github.com/NicosaurusRex99/DivineRPG/issues/15
https://github.com/TheSlayerMC/Journey-1.12/issues/1

Currently DRPG uses "EntityRegistry", which is old stuff and recommended against (see https://mcforge.readthedocs.io/en/latest/concepts/registries/) and not the event registry which is recommended in that page. As a result, the entities and spawn egg colors are manually registered. Turns out when a spawn egg is registered, mob statistics are also registered, and this mod registers the spawn eggs through manual creation of an EntityEggInfo class.

The stacktrace in the first crash points to line 962 (at the time), where an EntityEggInfo is manually created:
https://github.com/NicosaurusRex99/DivineRPG/blob/1eebf2e78ef4eaaa3a419fd54944b80843a2ac92/src/main/java/naturix/divinerpg/registry/ModEntities.java#L962

Apparently the EntityEggInfo contains the statistics and this is what causes the issue.
But in the pull request I remove that code and use EntityEntryBuilder instead:

https://github.com/Immortallis1/DivineRPG/blob/0c7e35e94fd4b89e6738f576058724c4ef0418d4/src/main/java/naturix/divinerpg/registry/ModEntities.java#L397

which, in its build() method, automatically creates a new statistic ("StatBase" class) and sets it:
https://github.com/MinecraftForge/MinecraftForge/blob/9de91930620634eaa0d0910721de96c4ebf6dd09/src/main/java/net/minecraftforge/fml/common/registry/EntityEntryBuilder.java#L272

I did a search through the project of "StatBase" and nothing came up. So basically:
-crash revolves around statistics
-using EntityEntryBuilder creates the statistic automatically
-before this PR EntityEntryBuilder is not used, and StatBase constructor isn't used either

Think this is enough to suggest that using EntityEntryBuilder and the registry events should fix the problem, as EEB does the stat creation for you.

-----------

To prove that two mods with the same mob id but different mod identifiers such as "divinerpg:crab" and "myothermod:crab" should NOT cause issues temporarily changed one of this mod's ids to match another one, creating the duplicate.
In this case, AOA3 has a mob named "Charger", and its id is "aoa3:charger". So I picked a random mob and changed its id to "charger" and for good measure changed the lang file too to include an entry for it.

https://cdn.discordapp.com/attachments/612350548167098389/612654808263819265/charger.PNG
https://cdn.discordapp.com/attachments/612350548167098389/612655339241734163/unknown.png

As a result now I have "divinerpg:charger" and "aoa3:charger".

Then I created a new world and did /summon for both divinerpg:charger and aoa3:charger (/summon proves that the ids have, in fact, been changed and do match). I was able to kill them and get killed by them, and the statistics updated just fine without causing a crash. It still worked fine after leaving and rejoining the world and restarting Minecraft entirely and killing more of both.

Here is a video of me doing the above:
https://www.youtube.com/watch?v=ny2mQorCt-g

As you can see, the statistics both update, even though both mobs have the same mob id but different mod identifiers, and even the same lang file name "Charger". This proves that having two mobs with the same id but different identifiers (divinerpg:charger and aoa3:charger) **shouldn't cause any issues inherently.**

As a result, the issue is something on either DRPG's side or crab mod/JITL side...or both (see below).

-----------

AoA didn't crash but that mod uses EntityEntityBuilder and registry events.

As for why JITL crashed, they also use the outdated EntityRegistry (which is old and not recommended) instead of EntityEntryBuilder/registry events. My guess is that when it's not set properly by creating a new StatBase like is done in EntityEntryBuilder, it defaults to something, and when **two mods that use the outdated method do this that have the same mob ids it causes a problem.** 

I tested the outdated EntityRegistry code with AoA using the identical charger ids as above and it still worked, so this probably will only cause crashes if the other mod is doing it improperly as well (as AoA does do it properly). As a result, fixing this code should prevent future issues, even if the other mod (see: JITL) does it improperly, as both need to be doing this improperly (rare) and have mob ids with the same name (also rare) to cause the problem.

As for the "crab" mob from the first issue, we don't know what the mod is because the OP didn't give the mods but it's a safe bet that it also uses the outdated EntityRegistry too.

**Comment by NicosaurusRex99** [comment]
Ill allow @krwminer to decide

**Comment by krwminer** [comment]
Thanks for doing all the research. I found it annoying to have to include the extra "divinerpg" also and had to revert a change I made to fix that. I will push this merge.

**Pull request merged**
