### PR TITLE
Proposing organization change for loot tables only

### PR DESCRIPTION
**Pull request by AstralScourge**
starting from scratch because mess

### CODE REVIEW

**Comment by NicosaurusRex99** [comment]
@krwminer @LiteWolf101 seem legit?


@Immortallis1 u in our discord?

**Comment by NicosaurusRex99** [comment]
@Immortallis1 we have discussed this in the discord. We like the loot table changes, we are unsure about the entity class location changes

**Comment by AstralScourge** [comment]
Which loot table changes did you say you liked? I'll just revert the entity class location changes if you don't like them.

**Comment by NicosaurusRex99** [comment]
we arent huge into this format 

```vanilla.boss.AncientEntity, arcana.boss.Parasecta, vethea.boss.Karos, vethea.npc.TheHunger, vanilla.pet.Smelter, arcana.pet.Seimer```

**Comment by AstralScourge** [comment]
Will undo now

**Comment by AstralScourge** [comment]
Which is better (for loot tables):
```entities/twilight/eden/Greenfeet``` or
```entities/twilight/Greenfeet```

**Comment by AstralScourge** [comment]
Ok, undid the class format thing. Classes are exactly back to how they were before (except for eden cadillion/tomo being in the arcana package for some reason). All mobs should be directly in their dimension package now, with twilight mobs being directly in the twilight package (e.g. twilight.EdenCadillion)

**Comment by Immortallis1** [comment]
dammit forgot something

**Comment by NicosaurusRex99** [comment]
@krwminer seem better?

**Comment by AstralScourge** [comment]
this is just getting messy now, will probably start from scratch

**Pull request closed without merging**
